<a href="https://colab.research.google.com/github/anujaroselakra1999/Machine-Learning-Models/blob/main/house_pricing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from sklearn.datasets import load_boston

In [ ]:
df = load_boston()

In [ ]:
print(df)

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]]), 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 1

In [ ]:
x = df['data']
y = df['target']

In [ ]:
print(x)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [ ]:
print(y)

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

In [ ]:
print(x.shape)
print(y.shape)

(506, 13)
(506,)


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

Multiple Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
regressor_1 = LinearRegression()
regressor_1.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = regressor_1.predict(x_test)

In [ ]:
np.set_printoptions(precision = 2)


In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred))

0.635463843320211


Support Vector Regression

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()

x_svr = sc_x.fit_transform(x_train)


In [ ]:
from sklearn.svm import SVR
regressor_2 = SVR(kernel = 'rbf')
regressor_2.fit(x_svr, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
y_pred1 = regressor_2.predict(sc_x.transform(x_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred1.reshape(len(y_pred1),1), y_test.reshape(len(y_test),1)),1))

[[25.12 22.6 ]
 [18.92 50.  ]
 [24.5  23.  ]
 [13.37  8.3 ]
 [20.94 21.2 ]
 [19.44 19.9 ]
 [20.81 20.6 ]
 [20.14 18.7 ]
 [18.95 16.1 ]
 [18.94 18.6 ]
 [20.78  8.8 ]
 [13.25 17.2 ]
 [14.76 14.9 ]
 [13.1  10.5 ]
 [27.11 50.  ]
 [30.44 29.  ]
 [21.4  23.  ]
 [31.76 33.3 ]
 [28.86 29.4 ]
 [21.43 21.  ]
 [23.85 23.8 ]
 [21.52 19.1 ]
 [18.91 20.4 ]
 [27.95 29.1 ]
 [20.4  19.3 ]
 [18.05 23.1 ]
 [17.16 19.6 ]
 [18.6  19.4 ]
 [33.88 38.7 ]
 [18.59 18.7 ]
 [15.23 14.6 ]
 [17.31 20.  ]
 [19.55 20.5 ]
 [21.21 20.1 ]
 [25.85 23.6 ]
 [20.9  16.8 ]
 [12.04  5.6 ]
 [22.28 50.  ]
 [13.94 14.5 ]
 [13.25 13.3 ]
 [23.48 23.9 ]
 [20.14 20.  ]
 [22.88 19.8 ]
 [14.98 13.8 ]
 [25.06 16.5 ]
 [23.25 21.6 ]
 [18.86 20.3 ]
 [20.91 17.  ]
 [16.88 11.8 ]
 [23.01 27.5 ]
 [20.73 15.6 ]
 [19.71 23.1 ]
 [21.38 24.3 ]
 [29.85 42.8 ]
 [15.22 15.6 ]
 [21.01 21.7 ]
 [19.88 17.1 ]
 [18.35 17.2 ]
 [19.54 15.  ]
 [21.6  21.7 ]
 [20.87 18.6 ]
 [20.91 21.  ]
 [31.74 33.1 ]
 [28.31 31.5 ]
 [18.34 20.1 ]
 [29.89 29.8 ]
 [16.14 15

In [ ]:
print(r2_score(y_test, y_pred1))

0.5084292459321271


Polynomial Regression

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree = 2)
x_poly = pf.fit_transform(x_train)
regressor_3 = LinearRegression()
regressor_3.fit(x_poly, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred2 = regressor_3.predict(pf.transform(x_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred2.reshape(len(y_pred2),1), y_test.reshape(len(y_test),1)),1))

[[ 26.23  22.6 ]
 [ 25.52  50.  ]
 [ 26.47  23.  ]
 [ 10.2    8.3 ]
 [ 21.91  21.2 ]
 [ 17.09  19.9 ]
 [ 18.91  20.6 ]
 [ 19.53  18.7 ]
 [ 10.49  16.1 ]
 [  9.75  18.6 ]
 [ -0.35   8.8 ]
 [  6.9   17.2 ]
 [ 14.54  14.9 ]
 [  8.69  10.5 ]
 [ 46.88  50.  ]
 [ 32.01  29.  ]
 [ 21.84  23.  ]
 [ 40.78  33.3 ]
 [ 30.42  29.4 ]
 [ 20.18  21.  ]
 [ 24.85  23.8 ]
 [ 21.84  19.1 ]
 [ 22.11  20.4 ]
 [ 26.1   29.1 ]
 [ 16.89  19.3 ]
 [ 31.71  23.1 ]
 [ 16.43  19.6 ]
 [ 19.34  19.4 ]
 [ 36.35  38.7 ]
 [ 15.9   18.7 ]
 [ 16.14  14.6 ]
 [ 18.12  20.  ]
 [ 18.26  20.5 ]
 [ 21.27  20.1 ]
 [ 26.68  23.6 ]
 [ 18.9   16.8 ]
 [  8.68   5.6 ]
 [ 37.19  50.  ]
 [ 13.65  14.5 ]
 [ 12.06  13.3 ]
 [ 25.26  23.9 ]
 [ 19.99  20.  ]
 [ 22.86  19.8 ]
 [ 18.8   13.8 ]
 [ 18.32  16.5 ]
 [ 21.57  21.6 ]
 [ 21.95  20.3 ]
 [  7.23  17.  ]
 [ 11.02  11.8 ]
 [ 23.75  27.5 ]
 [-21.41  15.6 ]
 [ 21.27  23.1 ]
 [ 21.59  24.3 ]
 [ 59.01  42.8 ]
 [  3.77  15.6 ]
 [ 21.8   21.7 ]
 [ 16.01  17.1 ]
 [ 17.54  17.2 ]
 [ 11.7   15. 

In [ ]:
print(r2_score(y_test, y_pred2))

0.5515683997226908


Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state = 0)
dtr.fit(x_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [ ]:
y_pred3 = dtr.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred3.reshape(len(y_pred3),1), y_test.reshape(len(y_test),1)),1))

[[23.7 22.6]
 [24.7 50. ]
 [23.3 23. ]
 [16.3  8.3]
 [21.1 21.2]
 [20.4 19.9]
 [20.6 20.6]
 [20.5 18.7]
 [15.3 16.1]
 [16.1 18.6]
 [10.5  8.8]
 [17.9 17.2]
 [14.2 14.9]
 [ 7.2 10.5]
 [50.  50. ]
 [37.  29. ]
 [21.4 23. ]
 [34.9 33.3]
 [24.1 29.4]
 [20.3 21. ]
 [24.7 23.8]
 [17.4 19.1]
 [20.1 20.4]
 [24.7 29.1]
 [22.2 19.3]
 [10.9 23.1]
 [14.5 19.6]
 [17.8 19.4]
 [39.8 38.7]
 [18.3 18.7]
 [14.1 14.6]
 [19.1 20. ]
 [24.7 20.5]
 [22.2 20.1]
 [22.4 23.6]
 [21.7 16.8]
 [10.2  5.6]
 [22.6 50. ]
 [12.1 14.5]
 [17.9 13.3]
 [23.9 23.9]
 [24.5 20. ]
 [22.  19.8]
 [14.1 13.8]
 [29.6 16.5]
 [20.5 21.6]
 [22.4 20.3]
 [13.5 17. ]
 [13.4 11.8]
 [28.7 27.5]
 [13.2 15.6]
 [19.8 23.1]
 [23.8 24.3]
 [21.9 42.8]
 [14.8 15.6]
 [18.9 21.7]
 [19.7 17.1]
 [17.5 17.2]
 [10.9 15. ]
 [22.4 21.7]
 [20.6 18.6]
 [22.2 21. ]
 [31.5 33.1]
 [22.8 31.5]
 [23.2 20.1]
 [22.8 29.8]
 [18.4 15.2]
 [18.9 15. ]
 [10.4 27.5]
 [22.2 22.6]
 [21.1 20. ]
 [22.2 21.4]
 [24.8 23.5]
 [30.1 31.2]
 [26.5 23.7]
 [ 7.2  7.4]
 [41.7 48.3]

In [ ]:
print(r2_score(y_test, y_pred3))

0.6125205090458208


Random Forest 

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(n_estimators = 20, random_state = 0)
rfr.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=20, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [ ]:
y_pred4 = rfr.predict(x_test)

In [ ]:
print(r2_score(y_test, y_pred4))

0.8148826152949457


As we can see that our model of Random Forest Regressor gives the best results or the r2 score therefore that model is considered over others.